import { test, expect } from '@playwright/test'
import { launchDaymate, robotWindow, workbenchWindow, getRobotStatesStable } from './helpers'

// Approval-from-robot end-to-end (Spec §21 M4 / §15 / §18). Run the Draft
// Review preset (an R3 `email.create_draft` approval step) → the robot enters
// need_approval; the Review deep-link opens the workbench at Approvals;
// approving resumes the run, creates the draft (mock), and returns the robot to
// done/idle. Exercises content-immutability hashing at resume with
// field-templated args ({{gmailEmails[0].…}}).
test.describe('approval from robot', () => {
  test('pauses for approval, deep-links to Approvals, resume on approve', async () => {
    const app = await launchDaymate()
    try {
      const robot = await robotWindow(app)
      const workbench = await workbenchWindow(app)

      // Trigger the Draft Review routine (manual). It lists Gmail, then hits
      // the R3 create_draft approval step and pauses.
      const run = await workbench.evaluate(() =>
        (window as unknown as {
          daymate: { runRoutine: (id: string) => Promise<{ id: string; status: string }> }
        }).daymate.runRoutine('draft_review')
      )
      expect(run.status).toBe('waiting_approval')

      // Robot reflects the pending approval (sticky need_approval state).
      const paused = await getRobotStatesStable(robot, (s) => s === 'need_approval', 10_000)
      expect(paused).toBe('need_approval')

      // A pending approval exists.
      const approvalsBefore = await workbench.evaluate(() =>
        (window as unknown as { daymate: { listApprovals(): Promise<{ id: string; status: string; toolName: string }[]> } })
          .daymate.listApprovals()
      )
      const pending = approvalsBefore.filter((a) => a.status === 'pending')
      expect(pending.length).toBe(1)
      expect(pending[0].toolName).toBe('email.create_draft')

      // Tone-mirroring (Spec §13.5): the draft body is generated by the
      // `generate_draft_reply` agent step from the user's OWN prior-reply voice
      // (mock Gmail SENT_FIXTURES → "Hi Alice," greeting + "Thanks for the
      // heads up." sign-off), NOT a generic canned string. The approval preview
      // carries the resolved `body` arg (contentHash is over resolved args §15).
      const preview = (
        pending[0] as unknown as { preview: { body?: string } }
      ).preview
      expect(preview.body).toContain('Hi Alice,')
      expect(preview.body).toContain('Thanks for the heads up.')
      expect(preview.body).not.toBe('收到——我会查看并尽快回复你。')

      // The robot "Review" deep-link opens the workbench at Approvals (the
      // same openWorkbenchAt('Approvals') call the bubble/panel button makes).
      await workbench.evaluate(() =>
        (window as unknown as { daymate: { openWorkbenchAt: (p: string) => Promise<void> } })
          .daymate.openWorkbenchAt('Approvals')
      )
      // The Approvals page renders its distinctive copy + the pending card.
      await expect(workbench.getByText('在你批准之前，什么都不会发出。')).toBeVisible()
      await expect(workbench.getByRole('button', { name: '批准并发送' })).toBeVisible()

      // Approve → the gated action runs under the approval context (content
      // hash rechecked at resume) and the run completes.
      await workbench.getByRole('button', { name: '批准并发送' }).click()

      // Robot returns to done (then idle after the auto-reset).
      const resolved = await getRobotStatesStable(
        robot,
        (s) => s === 'done' || s === 'idle',
        10_000
      )
      expect(['done', 'idle']).toContain(resolved)

      // The approval is now executed (the draft was created).
      const approvalsAfter = await workbench.evaluate(() =>
        (window as unknown as { daymate: { listApprovals(): Promise<{ id: string; status: string }[]> } })
          .daymate.listApprovals()
      )
      const mine = approvalsAfter.find((a) => a.id === pending[0].id)
      expect(mine?.status).toBe('executed')
    } finally {
      await app.close()
    }
  })
})
