// IPC contract mirror for the main process.
// The canonical types live in src/shared so both sides import the same shape.
// This file exists per spec §7 repo structure to keep main-side wiring local.

export { IPC } from '@shared/constants'
export type {
  DaymateApi,
  RobotState,
  RobotView,
  AppInfo,
  WindowName,
  TaskUpdate,
  Task,
  RoutineDefinition,
  RoutineRun,
  RoutineRunStep,
  RoutineUpdate,
  NeedToKnow,
  ActivityEvent,
  ApprovalRequest,
  LlmConfig,
  LlmConfigInput,
  LlmTestResult,
  LlmProvider,
  RobotNotify,
  WorkbenchPage,
  MemoryItem,
  MemorySaveInput,
  MemoryUpdate,
  MemoryKey,
  ApplicationView,
  ApplicationCreateInput,
  ApplicationEventInput,
  ApplicationUpdateFields,
  InterviewNoteInput,
  InterviewNote,
  ResumeVersion,
  PrepMaterial,
  EmailMatchProposal,
  JobSearchSettings,
  BossStatus,
  ApplicationFunnelStats,
  FunnelReviewOutput,
  JobMatchOutput,
  JobRecommendations,
  FetchJobRecommendationsOpts,
  BossJob,
  NotificationPrefs,
  BirthData,
  TaskCreateInput,
  WeatherBriefing,
  TodoSettings
} from '@shared/types'
