// Real Boss Provider — wraps the `boss` CLI (jackwener/boss-cli, PyPI
// `kabi-boss-cli`) as a subprocess. boss-cli handles auth entirely (cookies
// auto-extracted from local browsers, 7-day TTL refresh), so Daymate touches no
// credential. Every command is invoked with `--json`; boss-cli prints Rich
// diagnostics to stderr (which we ignore) and the `{ok,schema_version,data}`
// envelope to stdout (which we parse).
//
// FIELD-MAPPING CAVEAT: boss-cli's envelope `data` shape is reverse-engineered
// and only partially documented in its SCHEMA.md (the per-command payload
// fields are not exhaustively listed). The mappers below read a few common
// field-name variants defensively; if real output uses a different key the
// resulting DTO simply omits the optional field (no crash). The mock provider
// drives every test, so this real path is exercised only when the user has
// boss-cli installed — adjust the mappers then against real output.
//
// boss-cli is ESM-ish Python, spawned via `execFile('boss', …)`. If `boss` is
// not on PATH (not installed), `getStatus` returns 'disconnected' and the
// container falls back to the mock — the credential-free dev path is unaffected.

import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import type {
  IntegrationAccount,
  IntegrationStatus,
  BossJob,
  BossApplication,
  BossInterview,
  BossChat,
  BossSearchQuery
} from '@shared/types'
import type { BossProvider } from './boss-provider'
import { BossCliError } from './boss-provider'
import { nowIso } from '../../util/ids'

const execFileAsync = promisify(execFile)
const ACCOUNT_ID = 'boss-real'
const BOSS_BIN = process.env.DAYMATE_BOSS_BIN ?? 'boss'
const SPAWN_TIMEOUT_MS = 60_000

/** The boss-cli `{ok, data, error}` envelope. */
interface Envelope<T> {
  ok: boolean
  schema_version?: string
  data: T | null
  error?: { code: string; message: string }
}

/**
 * Auto-relogin on `__zp_stoken__` expiry.
 *
 * boss-cli's `__zp_stoken__` is generated by zhipin.com client-side JS and
 * drops periodically (anti-bot server-side invalidation, not storage loss).
 * With camoufox installed, `boss login --refresh-stoken` regenerates it
 * **non-interactively** — it reuses the saved session cookies + runs headless
 * camoufox so the site JS re-mints the token. No QR scan, no browser cookie
 * extraction. If the session cookies themselves have expired, the refresh
 * fails (exit 1) and we surface the original error so the user does a manual
 * `boss login --qrcode`.
 *
 * Constraints:
 *  - only ONE retry per call (no re-login loop).
 *  - a module-wide cooldown + a shared in-flight promise so concurrent
 *    failing searches coalesce into a single camoufox run (the anti-bot
 *    trips on rapid back-to-back logins just as it does on rapid searches).
 *  - gated to stoken-specific `not_authenticated` errors (message mentions
 *    `__zp_stoken__` / `环境异常`); funnel reads (`applied`/`interviews`/
 *    `chat`) work without stoken per decision 0017, so a not_authenticated
 *    there means real session expiry → no point trying stoken refresh.
 */
let refreshInFlight: Promise<boolean> | null = null
let lastRefreshAt = 0
const REFRESH_COOLDOWN_MS = 60_000

function isStokenExpiryError(e: unknown): e is BossCliError {
  return (
    e instanceof BossCliError &&
    e.code === 'not_authenticated' &&
    (e.message.includes('__zp_stoken__') || e.message.includes('环境异常'))
  )
}

async function refreshStokenOnce(): Promise<boolean> {
  // Coalesce concurrent callers into one camoufox run.
  if (refreshInFlight) return refreshInFlight
  const now = Date.now()
  if (now - lastRefreshAt < REFRESH_COOLDOWN_MS) return false
  lastRefreshAt = now
  refreshInFlight = (async () => {
    try {
      await execFileAsync(BOSS_BIN, ['login', '--refresh-stoken'], {
        timeout: SPAWN_TIMEOUT_MS,
        maxBuffer: 16 * 1024 * 1024,
        windowsHide: true
      })
      return true
    } catch {
      return false
    } finally {
      refreshInFlight = null
    }
  })()
  return refreshInFlight
}

/** Run `boss <args> --json`; on a stoken-expiry, auto-refresh + retry once. */
async function runBossWithRelogin<T>(args: string[]): Promise<T> {
  try {
    return await runBoss<T>(args)
  } catch (err) {
    if (!isStokenExpiryError(err)) throw err
    const refreshed = await refreshStokenOnce()
    if (!refreshed) throw err
    return runBoss<T>(args) // retry exactly once
  }
}

/** Run `boss <args> --json` and return the parsed `data`, or throw BossCliError. */
async function runBoss<T>(args: string[]): Promise<T> {
  let stdout: string
  try {
    const res = await execFileAsync(BOSS_BIN, [...args, '--json'], {
      timeout: SPAWN_TIMEOUT_MS,
      maxBuffer: 16 * 1024 * 1024,
      windowsHide: true
    })
    stdout = res.stdout
  } catch (err) {
    const e = err as { code?: string; message?: string; stdout?: string }
    // ENOENT = the `boss` binary is not installed.
    if (e.code === 'ENOENT') {
      throw new BossCliError('未安装 boss-cli（找不到 boss 命令）', 'not_installed')
    }
    // execFile rejects on non-zero exit; boss-cli may still have written a
    // JSON error envelope to stdout before exiting.
    const stdoutMaybe = e.stdout ?? ''
    if (stdoutMaybe.trim()) {
      const env = parseEnvelope<T>(stdoutMaybe)
      if (env && !env.ok) {
        throw new BossCliError(env.error?.message ?? 'boss-cli 调用失败', mapCode(env.error?.code))
      }
    }
    throw new BossCliError(e.message ?? 'boss-cli 调用失败', 'unknown_error')
  }
  const env = parseEnvelope<T>(stdout)
  if (!env) throw new BossCliError('boss-cli 输出无法解析', 'unknown_error')
  if (!env.ok || env.data == null) {
    throw new BossCliError(env.error?.message ?? 'boss-cli 返回错误', mapCode(env.error?.code))
  }
  return env.data
}

function parseEnvelope<T>(stdout: string): Envelope<T> | null {
  const trimmed = stdout.trim()
  if (!trimmed) return null
  try {
    return JSON.parse(trimmed) as Envelope<T>
  } catch {
    return null
  }
}

function mapCode(code?: string): BossCliError['code'] {
  switch (code) {
    case 'not_authenticated':
    case 'rate_limited':
    case 'invalid_params':
    case 'api_error':
      return code
    default:
      return 'unknown_error'
  }
}

// Defensive field readers: try several likely key names, return the first hit.
function pick(obj: Record<string, unknown>, keys: string[]): unknown {
  for (const k of keys) {
    if (obj[k] != null && obj[k] !== '') return obj[k]
  }
  return undefined
}
function str(obj: Record<string, unknown>, keys: string[]): string | undefined {
  const v = pick(obj, keys)
  return typeof v === 'string' ? v : v != null ? String(v) : undefined
}

/** `boss search`/`recommend` job shape (from search.py `_render_job_table`):
 *  flat `{securityId, jobName, brandName, salaryDesc, jobExperience, jobDegree,
 *  cityName, areaDistrict, skills}`. */
function mapJob(d: Record<string, unknown>): BossJob {
  return {
    provider: 'boss',
    accountId: ACCOUNT_ID,
    securityId: String(d.securityId ?? d.security_id ?? d.encryptId ?? d.encrypt_id ?? ''),
    jobName: String(d.jobName ?? d.job_name ?? d.position ?? d.postName ?? ''),
    companyName: String(d.companyName ?? d.brandName ?? d.company ?? ''),
    salary: str(d, ['salaryDesc', 'salary']),
    city: str(d, ['cityName', 'city', 'locationName', 'areaDistrict']),
    experience: str(d, ['jobExperience', 'experienceName', 'experience', 'postAge']),
    degree: str(d, ['jobDegree', 'degreeName', 'degree', 'education']),
    hrName: str(d, ['bossName', 'hrName', 'activeTimeDesc']),
    brandName: str(d, ['brandName', 'companyName']),
    jobLabels: Array.isArray(d.skills)
      ? (d.skills as string[])
      : Array.isArray(d.jobLabels)
        ? (d.jobLabels as string[])
        : undefined
  }
}

/** `boss detail <securityId>` data shape (from search.py `_render_detail`):
 *  nested `{jobInfo:{jobName,salaryDesc,experienceName|jobExperience,degreeName|jobDegree,
 *  locationName|cityName,skills,postDescription|jobDesc}, bossInfo:{name,title},
 *  brandComInfo:{brandName,…}}`. `jobInfo` may be absent → fall back to `data`
 *  itself (some envelopes inline the job at the top level). */
function mapJobDetail(d: Record<string, unknown>, securityId: string): BossJob {
  const job = (d.jobInfo as Record<string, unknown> | undefined) ?? d
  const brand = (d.brandComInfo as Record<string, unknown> | undefined) ?? (d.brandInfo as Record<string, unknown> | undefined) ?? d
  const boss = (d.bossInfo as Record<string, unknown> | undefined) ?? {}
  return {
    provider: 'boss',
    accountId: ACCOUNT_ID,
    securityId: String(job.securityId ?? securityId ?? ''),
    jobName: String(str(job, ['jobName', 'job_name', 'positionName']) ?? ''),
    companyName: String(str(brand, ['brandName', 'companyName']) ?? ''),
    salary: str(job, ['salaryDesc', 'salary']),
    city: str(job, ['locationName', 'cityName', 'city', 'areaDistrict']),
    experience: str(job, ['experienceName', 'jobExperience', 'experience']),
    degree: str(job, ['degreeName', 'jobDegree', 'degree']),
    hrName: str(boss, ['name', 'bossName', 'hrName']),
    hrTitle: str(boss, ['title', 'bossTitle']),
    brandName: str(brand, ['brandName', 'companyName']),
    industry: str(brand, ['industryName', 'industry']),
    scale: str(brand, ['scaleName', 'companyScale', 'scale']),
    stage: str(brand, ['stageName', 'financeStage', 'stage']),
    areaDistrict: str(job, ['areaDistrict', 'area']),
    businessDistrict: str(job, ['businessDistrict']),
    // JD body (postDescription|jobDesc) — untrusted boss data; the renderer
    // renders as text (React escapes) never as HTML (§17.12/§17.13).
    jobDescription: str(job, ['postDescription', 'jobDesc', 'jobDescHtml', 'description']),
    jobLabels: Array.isArray(job.skills)
      ? (job.skills as string[])
      : Array.isArray(job.jobLabels)
        ? (job.jobLabels as string[])
        : undefined
  }
}

/** `boss applied` card shape (from personal.py `_render`): nested
 *  `{jobInfo:{jobName,salaryDesc,securityId,…}, brandInfo:{brandName,…},
 *  deliverStatusDesc|statusDesc, updateTimeDesc|createTimeDesc}`.
 *  `jobInfo`/`brandInfo` may be absent in some envelope variants → fall back
 *  to the card itself (defensive, matches the render code's `card.get(jobInfo, card)`). */
function mapApplication(d: Record<string, unknown>): BossApplication {
  const job = (d.jobInfo as Record<string, unknown> | undefined) ?? d
  const brand = (d.brandInfo as Record<string, unknown> | undefined) ?? d
  return {
    provider: 'boss',
    accountId: ACCOUNT_ID,
    securityId: String(
      pick(job, ['securityId', 'security_id', 'encryptId', 'encryptJobId']) ??
      pick(d, ['securityId', 'security_id', 'encryptJobId']) ?? ''
    ),
    jobName: String(str(job, ['jobName', 'job_name', 'positionName']) ?? ''),
    companyName: String(str(brand, ['brandName', 'companyName', 'companyShortName']) ?? ''),
    salary: str(job, ['salaryDesc', 'salary']),
    city: str(job, ['cityName', 'city', 'locationName']),
    brandName: str(brand, ['brandName', 'companyName']),
    hrName: str(d, ['bossName', 'hrName', 'friendName', 'name']),
    appliedAt: str(d, ['updateTimeDesc', 'createTimeDesc', 'addTime', 'applyTime', 'createTime'])
  }
}

function mapInterview(d: Record<string, unknown>): BossInterview {
  return {
    provider: 'boss',
    accountId: ACCOUNT_ID,
    securityId: str(d, ['securityId', 'security_id', 'encryptJobId']) as string | undefined,
    interviewId: String(d.id ?? d.encryptId ?? d.interviewId ?? ''),
    jobName: String(d.jobName ?? d.positionName ?? d.job_name ?? ''),
    companyName: String(d.companyName ?? d.brandName ?? d.companyShortName ?? ''),
    interviewTime: str(d, ['interviewTime', 'expectTime', 'time']),
    address: str(d, ['address', 'addressDesc', 'location']),
    contact: str(d, ['contact', 'bossName', 'hrName']),
    status: str(d, ['status', 'statusDesc', 'interviewStatus'])
  }
}

function mapChat(d: Record<string, unknown>): BossChat {
  return {
    provider: 'boss',
    accountId: ACCOUNT_ID,
    friendId: String(d.encryptUid ?? d.friendId ?? d.encryptFriendId ?? d.encryptGeekId ?? d.id ?? ''),
    hrName: str(d, ['name', 'bossName', 'hrName', 'friendName']),
    companyName: str(d, ['companyName', 'brandName']),
    jobName: str(d, ['jobName', 'positionName']),
    lastMessage: str(d, ['lastMsg', 'lastText', 'lastContent', 'lastMessage']),
    lastTime: str(d, ['lastTime', 'updateTime', 'lastCreateTime']),
    unread: typeof d.unread === 'boolean' ? d.unread : undefined,
    securityId: str(d, ['securityId', 'security_id', 'encryptJobId']) as string | undefined
  }
}

/** Normalize `boss <cmd> --json` `data` (object, array, or {<containerKey>:[…]}) → array.
 *  Container keys are the real boss-cli envelope field names, derived from the
 *  command render code: `cardList` (applied), `interviewList` (interviews),
 *  `result`/`friendList` (chat), `jobList` (search/recommend/history). The legacy
 *  generic keys (`list`,`results`…) stay as a tail fallback. */
function asArray(data: unknown): Record<string, unknown>[] {
  if (Array.isArray(data)) return data as Record<string, unknown>[]
  if (data && typeof data === 'object') {
    const o = data as Record<string, unknown>
    for (const k of [
      'cardList', 'interviewList', 'friendList', 'result', 'jobList',
      'list', 'applications', 'jobs', 'zpData', 'results'
    ]) {
      if (Array.isArray(o[k])) return o[k] as Record<string, unknown>[]
    }
    // `boss chat` with no conversations returns `data: {}` (no list key).
    // An empty object is NOT a record — return [] so we don't synthesize a
    // single all-empty entry. A non-empty object without a list key (rare
    // inline-record envelope) is wrapped as a single item.
    return Object.keys(o).length > 0 ? [o] : []
  }
  return []
}

export class BossCliProvider implements BossProvider {
  readonly provider = 'boss' as const
  readonly accountId = ACCOUNT_ID

  async connect(): Promise<IntegrationAccount> {
    // boss-cli auth is cookie-based (login happens in the browser + `boss login`
    // in a terminal); "connect" here = validate the saved session.
    const authenticated = await this.isAuthenticated()
    this._lastStatus = authenticated ? 'connected' : 'disconnected'
    return {
      id: ACCOUNT_ID,
      provider: 'boss',
      displayName: 'BOSS 直聘 (boss-cli)',
      status: authenticated ? 'connected' : 'disconnected',
      scopes: ['boss:read'],
      lastSyncAt: nowIso(),
      createdAt: nowIso(),
      updatedAt: nowIso()
    }
  }

  private _lastStatus: IntegrationStatus = 'disconnected'

  async disconnect(): Promise<void> {
    // No-op: we never clear boss-cli's cookies (that is `boss logout`, a manual
    // terminal action). Disconnect just marks Daymate's view as offline.
    this._lastStatus = 'disconnected'
  }

  /**
   * `boss status --json` → whether to swap the mock out for the real provider.
   * Never reads cookies. NOTE: `boss status --json` prints a FLAT object
   * ({credential_present, authenticated, …}), NOT the `{ok, data, error}`
   * envelope that list commands (applied/interviews/…) use — so it must be
   * exec'd + parsed directly; `runBoss` would reject it as a non-envelope.
   *
   * Gates on `credential_present` (a saved credential file exists) rather than
   * boss-cli's strict `authenticated` flag: that flag is false whenever the
   * browser-JS cookie `__zp_stoken__` is missing, even though the funnel read
   * APIs (`boss applied`/`interviews`/`chat`) work fine with the 4 session
   * cookies QR login grants. `__zp_stoken__` is only needed by `search`/
   * `recommend`, which degrade to a `provider_unavailable` Activity (the
   * existing error path) rather than blocking the funnel. So a present-but-
   * stoken-less credential still swaps to real — honest behavior for a
   * read-only P1 funnel. A truly absent session (`credential_present:false`)
   * stays mock; a later session that fully expires surfaces as an error
   * envelope on the next read.
   */
  private async isAuthenticated(): Promise<boolean> {
    try {
      const res = await execFileAsync(BOSS_BIN, ['status', '--json'], {
        timeout: SPAWN_TIMEOUT_MS,
        maxBuffer: 16 * 1024 * 1024,
        windowsHide: true
      })
      const obj = JSON.parse((res.stdout ?? '').trim() || '{}') as Record<string, unknown>
      const present = pick(obj, ['credential_present', 'credentialPresent', 'has_credential'])
      if (present === true || present === 'true') return true
      const auth = pick(obj, ['authenticated', 'isAuthenticated', 'logged_in', 'loggedIn'])
      return auth === true || auth === 'true'
    } catch (e) {
      // ENOENT (boss not installed), non-zero exit, or parse failure → mock.
      console.error(`[boss] isAuthenticated ERROR:`, e)
      return false
    }
  }

  async getStatus(): Promise<IntegrationStatus> {
    if (this._lastStatus === 'connected') {
      // Re-validate lazily; an expired session surfaces on the next read.
      return 'connected'
    }
    const ok = await this.isAuthenticated()
    this._lastStatus = ok ? 'connected' : 'disconnected'
    return this._lastStatus
  }

  /**
   * Interactive login — spawns `boss login` (no `--qrcode`).
   *
   * boss-cli's no-flag `login` is the **smart** path: it first tries to
   * extract cookies from a real browser (Chrome/Edge/Safari) where the user
   * is logged into zhipin.com, and only falls back to the camoufox QR flow
   * if browser extraction fails. The real-browser stoken is the **only**
   * stoken BOSS `search` accepts — camoufox's headless stoken is rejected
   * by anti-bot. So this ordering gives the user a chance at working 岗位
   * search without a terminal; the QR fallback still yields a valid session
   * for funnel reads (applied/interviews/chat) even when search is blocked.
   *
   * For the real-browser path to succeed the user must **fully quit** their
   * browser before clicking 登录 (browser-cookie3 cannot read the cookie
   * SQLite while the browser process holds it open). The renderer surfaces
   * this hint on the BOSS card.
   *
   * The QR image (fallback) opens in the system viewer (Preview) via
   * boss-cli's own `_open_image_file`. No cookie crosses to the renderer;
   * the cred lands in boss-cli's own credential file. Long timeout — the
   * user may need to scan + confirm on their phone.
   */
  async login(): Promise<{ success: boolean; message: string }> {
    try {
      await execFileAsync(BOSS_BIN, ['login'], {
        timeout: 180_000,
        maxBuffer: 16 * 1024 * 1024,
        windowsHide: true
      })
      return { success: true, message: 'BOSS 直聘登录成功' }
    } catch (e) {
      const err = e as { code?: string; stdout?: string; stderr?: string; message?: string }
      if (err.code === 'ENOENT') {
        return { success: false, message: '未安装 boss-cli（找不到 boss 命令）' }
      }
      // boss-cli exits non-zero on cancel/failure; surface the last line of its
      // Rich diagnostic so the renderer shows something actionable.
      const tail = (err.stderr || err.stdout || '')
        .split('\n')
        // eslint-disable-next-line no-control-regex -- strip ANSI color codes from boss-cli's Rich stderr
        .map((l) => l.replace(/\x1b\[[0-9;]*m/g, '').trim())
        .filter((l) => l.length > 0)
        .slice(-2)
        .join(' ')
      return { success: false, message: tail || err.message || '登录失败或超时' }
    }
  }

  /** `boss logout` — clears boss-cli's saved credential file. */
  async logout(): Promise<{ success: boolean; message: string }> {
    try {
      await execFileAsync(BOSS_BIN, ['logout'], {
        timeout: SPAWN_TIMEOUT_MS,
        maxBuffer: 16 * 1024 * 1024,
        windowsHide: true
      })
      return { success: true, message: '已退出 BOSS 直聘' }
    } catch (e) {
      const err = e as { code?: string; message?: string }
      if (err.code === 'ENOENT') {
        return { success: false, message: '未安装 boss-cli（找不到 boss 命令）' }
      }
      return { success: false, message: err.message || '退出失败' }
    }
  }

  async listApplications(): Promise<BossApplication[]> {
    const data = await runBoss<unknown>(['applied'])
    return asArray(data).map(mapApplication)
  }

  async listInterviews(): Promise<BossInterview[]> {
    const data = await runBoss<unknown>(['interviews'])
    return asArray(data).map(mapInterview)
  }

  async listChats(): Promise<BossChat[]> {
    const data = await runBoss<unknown>(['chat'])
    return asArray(data).map(mapChat)
  }

  async getJobDetail(securityId: string): Promise<BossJob> {
    // `boss detail` needs __zp_stoken__ → auto-refresh + retry on expiry.
    const data = await runBossWithRelogin<Record<string, unknown>>(['detail', securityId])
    return mapJobDetail(data, securityId)
  }

  async searchJobs(query: BossSearchQuery): Promise<BossJob[]> {
    return (await this.searchJobsPaged(query)).jobs
  }
  async searchJobsPaged(query: BossSearchQuery): Promise<{ jobs: BossJob[]; hasMore: boolean }> {
    const args = ['search', query.keyword]
    if (query.city) args.push('--city', query.city)
    if (query.salary) args.push('--salary', query.salary)
    if (query.experience) args.push('--exp', query.experience)
    if (query.degree) args.push('--degree', query.degree)
    if (query.industry) args.push('--industry', query.industry)
    if (query.scale) args.push('--scale', query.scale)
    if (query.stage) args.push('--stage', query.stage)
    if (query.jobType) args.push('--job-type', query.jobType)
    if (query.page) args.push('-p', String(query.page))
    // `boss search` needs __zp_stoken__ → auto-refresh + retry on expiry.
    const data = await runBossWithRelogin<unknown>(args)
    // boss search envelope: data = { jobList: [...], hasMore: bool }. Pull
    // `hasMore` from the data object before asArray flattens to the job list.
    const obj = data && typeof data === 'object' ? (data as Record<string, unknown>) : {}
    const hasMore = obj.hasMore === true || obj.has_more === true
    const jobs = asArray(data).map(mapJob)
    return { jobs: query.limit ? jobs.slice(0, query.limit) : jobs, hasMore }
  }
}

// Exported for unit tests that lock mappers to real boss-cli envelope shapes
// (derived from boss_cli/commands/*.py render code). These are pure data
// transforms with no side effects.
export {
  asArray,
  mapJob,
  mapJobDetail,
  mapApplication,
  mapInterview,
  mapChat
}
